In [23]:
import pandas as pd
import numpy as np

## DataFrame

A **DataFrame** is a two-dimensional tabular data structure in pandas.

It consists of:

- Rows (index)
- Columns
- Values

Each column can store a different data type:

- Numeric
- String
- Boolean
- Date/Time
- etc.

A DataFrame can be thought of as a **dictionary of Series** sharing the same row index.

### Characteristics

- Rectangular table of data.
- Rows and columns both have labels.
- Columns are ordered and named.
- Each column is a Series.
- Different columns can have different data types.

### Creating a DataFrame

One of the most common ways to create a DataFrame is from a dictionary of lists or NumPy arrays.

- Dictionary keys become column names.
- Dictionary values become column data.
- Pandas automatically creates a row index if none is provided.

### Column Order

Columns appear in the order of the dictionary keys (insertion order).

### Automatic Index

If no index is specified, pandas creates a default integer index:

```text
0, 1, 2, 3, ...
```

### Key Points

- A DataFrame is a 2D table.
- Rows and columns both have labels.
- Columns can have different data types.
- A DataFrame can be viewed as multiple Series sharing the same index.
- Dictionary keys become column names.
- Pandas automatically generates row indices when none are provided.

In [5]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Viewing Data with `head()` and `tail()`

When working with large DataFrames, it is often unnecessary to display the entire dataset.

### `head()`

The `head()` method returns the first 5 rows by default.

It is useful for:

- Quickly inspecting data
- Verifying column names
- Checking data loading results

### `tail()`

The `tail()` method returns the last 5 rows by default.

It is useful for:

- Inspecting the end of a dataset
- Verifying appended data
- Checking sorting results

### Custom Number of Rows

Both methods accept an optional argument:

- `head(n)` → first `n` rows
- `tail(n)` → last `n` rows

## Key Points

- `head()` displays the first 5 rows by default.
- `tail()` displays the last 5 rows by default.
- Both methods are useful for quick data inspection.
- A custom number of rows can be specified.

In [7]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [8]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [9]:
frame.head(3)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [10]:
frame.tail(2)

    state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Specifying Column Order

When creating a DataFrame, you can specify the order of columns using the `columns` parameter.

- Columns will appear in the order provided.
- This overrides the default dictionary key order.

## Adding Missing Columns

If a column specified in `columns` does not exist in the source data:

- Pandas creates the column automatically.
- All values are filled with `NaN`.

This is useful when defining a desired schema before data is available.

## Accessing Columns

A DataFrame column can be retrieved as a Series.

There are two common methods:

### Dictionary-style Access

Works for all column names.

### Attribute-style Access

Provides a convenient shortcut using dot notation.

However, it only works when:

- The column name is a valid Python identifier.
- The column name does not conflict with DataFrame methods.

### When Dot Notation Fails

Dot notation cannot be used when:

- Column names contain spaces.
- Column names contain special characters.
- Column names conflict with DataFrame methods.

In such cases, use dictionary-style access.

## Key Points

- Use `columns` to control column order.
- Missing columns are filled with `NaN`.
- DataFrame columns are returned as Series.
- `df["column"]` works for every column.
- `df.column` is only a convenience shortcut and has limitations.

In [11]:
pd.DataFrame(
    data,
    columns=["year", "state", "pop"]
)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [13]:
frame2 = pd.DataFrame(
    data,
    columns=["year", "state", "pop", "debt"]
)

frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [14]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [16]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [17]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

## Accessing Rows

Pandas provides two important accessors for selecting rows:

### `loc`

Selects rows by **label**.

### `iloc`

Selects rows by **integer position**.

Both return a Series representing the selected row.

---

## Modifying Columns

Columns can be updated using assignment.

### Assigning a Scalar

When a scalar value is assigned to a column:

- The value is broadcast to every row.

### Assigning an Array or List

When assigning an array or list:

- The length must match the number of rows in the DataFrame.

### Assigning a Series

When assigning a Series:

- Pandas aligns values using index labels.
- Labels that do not match the DataFrame index become `NaN`.
- Missing labels are ignored.

---

## Creating New Columns

Assigning to a column name that does not already exist automatically creates a new column.

A common pattern is creating Boolean columns from conditions.

---

## Deleting Columns

Columns can be removed using the `del` keyword.

This works similarly to deleting a key from a dictionary.

---

## Important Note: View vs Copy

When you access a column:

- Pandas usually returns a **view** of the underlying data.
- Modifying the returned Series may modify the original DataFrame.

To create an independent copy:

Use the Series `.copy()` method.

## Key Points

- `loc` selects rows by label.
- `iloc` selects rows by position.
- Scalars are broadcast to all rows during assignment.
- Lists and arrays must match DataFrame length.
- Series assignments align using index labels.
- Assigning to a new column name creates a new column.
- `del` removes columns.
- DataFrame columns are typically views, not copies.

In [18]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [19]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [21]:
frame2["debt"] = 16.5

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [25]:
frame2["debt"] = np.arange(6.)

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [27]:
val = pd.Series(
    [-1.2, -1.5, -1.7],
    index=["two", "four", "five"]
)

frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [38]:
frame2["eastern"] = frame2["state"] == "Ohio"

frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [39]:
del frame2["eastern"]  #New columns cannot be created with the frame2.eastern dot attribute notation.

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

## Creating a DataFrame from Nested Dictionaries

A DataFrame can be created from a dictionary of dictionaries.

In this structure:

- Outer dictionary keys become column names.
- Inner dictionary keys become row indices.
- Missing values are filled with `NaN`.

### Structure

```text
Outer Keys  → Columns
Inner Keys  → Row Index
Values      → Cell Values
```

### Resulting Alignment

Pandas automatically aligns values based on the inner dictionary keys.

If a value is missing for a particular row and column combination, pandas inserts `NaN`.

---

## Transposing a DataFrame

A DataFrame can be transposed using `.T`.

Transposing swaps:

```text
Rows    ↔ Columns
Index   ↔ Column Names
```

### Important Note

If columns have different data types:

- Type information may be lost after transposition.
- Columns may become generic Python object arrays.

---

## Specifying an Explicit Index

When an index is provided:

- Pandas uses the specified index.
- Missing entries become `NaN`.
- Extra inner dictionary keys are ignored if not included in the index.

---

## Creating a DataFrame from a Dictionary of Series

A dictionary of Series objects can also be used to create a DataFrame.

Pandas aligns the Series automatically using their index labels.

This behavior is similar to Series arithmetic alignment.

## Key Points

- Nested dictionaries create DataFrames naturally.
- Outer keys become columns.
- Inner keys become row labels.
- Missing values are filled with `NaN`.
- `.T` transposes rows and columns.
- Explicit indices override automatically generated indices.
- Dictionaries of Series are automatically aligned by index.

In [41]:
populations = {
    "Ohio": {
        2000: 1.5,
        2001: 1.7,
        2002: 3.6
    },
    "Nevada": {
        2001: 2.4,
        2002: 2.9
    }
}

frame3 = pd.DataFrame(populations)

frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [42]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [43]:
pd.DataFrame(
    populations,
    index=[2001, 2002, 2003]
)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [44]:
pdata = {
    "Ohio": frame3["Ohio"][:-1],
    "Nevada": frame3["Nevada"][:2]
}

pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

## Naming Rows and Columns

A DataFrame's index and columns can have names using:

- `index.name`
- `columns.name`

These names are displayed when the DataFrame is printed and help provide context to the data.

### Difference from Series

- Series has a `name` attribute.
- DataFrame does **not** have a `name` attribute.
- Instead, DataFrames can name their rows and columns separately.

---

## Converting a DataFrame to NumPy

Use the `to_numpy()` method to convert a DataFrame into a two-dimensional NumPy array.

### Characteristics

- Returns only the data values.
- Row and column labels are discarded.
- Result is a NumPy `ndarray`.

---

## Data Type Behavior

### Same Data Types

If all columns have compatible numeric types:

- The resulting NumPy array keeps a numeric dtype.

### Mixed Data Types

If columns contain different types (e.g., numbers and strings):

- NumPy chooses a common dtype that can hold all values.
- Usually this becomes `dtype=object`.

This allows different Python objects to be stored in the same array.

## Key Points

- `index.name` names the row index.
- `columns.name` names the columns.
- DataFrames do not have a `name` attribute.
- `to_numpy()` converts a DataFrame to a NumPy array.
- Labels are not included in the resulting array.
- Mixed column types typically produce `dtype=object`.

In [46]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [47]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [48]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)