In [1]:
import pandas as pd
import numpy as np

## Dropping Entries from an Axis

The `drop` method returns a **new object** with the specified labels removed from an axis.

- The original object is not modified.
- A single label or a list of labels can be dropped.

### On a Series

Pass one label or a list of labels to remove them from the index.

### On a DataFrame

Labels can be dropped from either axis:

| Approach | Drops from |
|----------|------------|
| `drop(index=[...])` | Row labels (axis 0) |
| `drop(columns=[...])` | Column labels (axis 1) |
| `drop([...], axis=1)` | Column labels (axis 1) — NumPy-style |
| `drop([...], axis="columns")` | Column labels (axis 1) — named-axis style |

## Key Points

- `drop` returns a new object — it does not modify in place.
- A single label or a list of labels can be passed.
- For DataFrames, use `index=` to drop rows and `columns=` to drop columns.
- `axis=1` and `axis="columns"` are equivalent alternatives for dropping columns.

In [2]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [3]:
new_obj = obj.drop("c")

new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [4]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [5]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"]
)

data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [8]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [9]:
data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14