In [2]:
import pandas as pd
import numpy as np

## NumPy ufuncs on pandas Objects

NumPy universal functions (ufuncs) operate **element-wise** and work directly on Series and DataFrames.

- Labels and index are preserved in the result.
- No special setup required — pass a pandas object where you would pass a NumPy array.

## Key Points

- NumPy ufuncs (e.g. `np.abs`, `np.sqrt`, `np.exp`) work element-wise on pandas objects.
- Index and column labels are retained in the output.

In [3]:
frame = pd.DataFrame(
    np.random.standard_normal((4, 3)),
    columns=list("bde"),
    index=["Utah", "Ohio", "Texas", "Oregon"]
)

frame

               b         d         e
Utah   -0.637292  1.481053 -0.260831
Ohio    1.107265  0.511838  2.079502
Texas  -0.022606 -1.534974 -0.666240
Oregon -0.777322  1.573640  1.194536

In [4]:
np.abs(frame)

               b         d         e
Utah    0.637292  1.481053  0.260831
Ohio    1.107265  0.511838  2.079502
Texas   0.022606  1.534974  0.666240
Oregon  0.777322  1.573640  1.194536

## `apply` — Applying a Function Along an Axis

`apply` applies a function to **each column or each row** of a DataFrame.

### Axis Behavior

| Argument | Function receives | Applied to |
|----------|-------------------|------------|
| `axis="index"` (default) | Each column as a Series | Per column |
| `axis="columns"` | Each row as a Series | Per row |

A helpful way to think about `axis="columns"`: the function is applied **across the columns** of each row.

### Return Value

- Function returns a **scalar** → result is a Series (one value per column or row).
- Function returns a **Series** → result is a DataFrame (each returned Series becomes a column).

### Note

Common reductions like `sum` and `mean` are built-in DataFrame methods — `apply` is not needed for those.

## Key Points

- `apply` passes each column (or row) as a Series to the function.
- Default axis is `"index"` → operates column-by-column.
- `axis="columns"` → operates row-by-row.
- Scalar return → Series result; Series return → DataFrame result.

In [5]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)  # applied per column

b    1.884587
d    3.108615
e    2.745742
dtype: float64

In [6]:
frame.apply(f1, axis="columns")  # applied per row

Utah      2.118345
Ohio      1.567664
Texas     1.512369
Oregon    2.350962
dtype: float64

In [7]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)  # function returns a Series → result is a DataFrame

            b         d         e
min -0.777322 -1.534974 -0.666240
max  1.107265  1.573640  2.079502

## Element-Wise Mapping: `applymap` and `map`

For applying a function to **every individual element**, pandas provides:

| Method | Object | Applies to |
|--------|--------|------------|
| `applymap(func)` | DataFrame | Every element in the DataFrame |
| `map(func)` | Series | Every element in the Series |

- `applymap` is the DataFrame equivalent of Series's `map`.
- Both return an object of the same shape with the function applied to each value.

## Key Points

- `applymap` applies an element-wise function across an entire DataFrame.
- `map` applies an element-wise function to every value in a Series.
- Both preserve the shape and labels of the original object.

In [8]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

/tmp/ipykernel_32023/2705683181.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

            b      d      e
Utah    -0.64   1.48  -0.26
Ohio     1.11   0.51   2.08
Texas   -0.02  -1.53  -0.67
Oregon  -0.78   1.57   1.19

In [9]:
frame["e"].map(my_format)

Utah      -0.26
Ohio       2.08
Texas     -0.67
Oregon     1.19
Name: e, dtype: object