In [1]:
import pandas as pd
import numpy as np

## Sorting by Index — `sort_index`

`sort_index` sorts a Series or DataFrame **lexicographically by its labels** and returns a new sorted object.

- The original object is not modified.
- Default sort order is **ascending**.
- Pass `ascending=False` for descending order.

### On a DataFrame

| Argument | Sorts |
|----------|-------|
| `sort_index()` | Row labels (axis 0) |
| `sort_index(axis="columns")` | Column labels (axis 1) |

## Key Points

- `sort_index` sorts by **labels**, not values.
- Returns a new object — does not modify in place.
- Default is ascending; use `ascending=False` for descending.
- For DataFrames, use `axis="columns"` to sort column labels.

In [2]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

obj

d    0
a    1
b    2
c    3
dtype: int64

In [3]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [4]:
frame = pd.DataFrame(
    np.arange(8).reshape((2, 4)),
    index=["three", "one"],
    columns=["d", "a", "b", "c"]
)

frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [5]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [6]:
frame.sort_index(axis="columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [7]:
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

## Sorting by Values — `sort_values`

`sort_values` sorts by the **data values** rather than the index labels.

### On a Series

- Sorts by value; the index follows along.
- `NaN` values are placed at the **end** by default.
- Use `na_position="first"` to place `NaN` at the start.

### On a DataFrame

- Pass a column name (or list of column names) as the sort key.
- When sorting by multiple columns, the first column is the primary key; subsequent columns break ties.

## Key Points

- `sort_values` sorts by data values, not labels.
- `NaN` is placed at the end by default; use `na_position="first"` to move it to the start.
- For DataFrames, pass one column name or a list of column names as sort keys.
- Earlier columns in the list take priority when sorting by multiple columns.

In [8]:
obj = pd.Series([4, 7, -3, 2])

obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [9]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [10]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [11]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [12]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [13]:
frame.sort_values(["a", "b"])  # sort by "a" first, then "b" to break ties

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

## Ranking — `rank`

`rank` assigns a rank to each value from **1** (lowest) to **n** (highest number of valid data points).

- By default, tied values are assigned their **average rank**.
- `NaN` values are excluded from ranking.
- Pass `ascending=False` to rank from highest to lowest.

### Tie-Breaking Methods

| `method` | Behavior |
|----------|----------|
| `"average"` | Default — assign the average rank to each tied entry |
| `"min"` | Use the minimum rank for all tied entries |
| `"max"` | Use the maximum rank for all tied entries |
| `"first"` | Assign ranks in the order the values appear in the data |
| `"dense"` | Like `"min"`, but ranks always increase by 1 between groups |

### On a DataFrame

- `rank()` ranks within each column by default (axis 0).
- `rank(axis="columns")` ranks each value relative to the other values in its row.

## Key Points

- `rank` assigns ordinal ranks starting from 1.
- Ties are broken with `method="average"` by default.
- `ascending=False` ranks the largest value as 1.
- For DataFrames, use `axis="columns"` to rank across each row.

In [14]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

obj.rank()  # tied values get average rank

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [15]:
obj.rank(method="first")  # tied values ranked by order of appearance

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [16]:
obj.rank(ascending=False)  # highest value gets rank 1

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [17]:
frame = pd.DataFrame({
    "b": [4.3, 7, -3, 2],
    "a": [0, 1, 0, 1],
    "c": [-2, 5, 8, -2.5]
})

frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [18]:
frame.rank(axis="columns")  # rank each value relative to others in its row

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0