In [2]:
import pandas as pd
import numpy as np

## Axis Indexes with Duplicate Labels

pandas does **not** require index labels to be unique — duplicates are permitted.

However, some operations (like `reindex`) do require unique labels.

### Checking for Uniqueness

Use the `is_unique` property on an index to check whether all labels are unique:

```python
obj.index.is_unique  # True or False
```

### Selection Behavior with Duplicate Labels

The return type of label-based indexing depends on whether the label is duplicated:

| Label in index | `obj[label]` returns |
|----------------|----------------------|
| Unique (appears once) | Scalar value |
| Duplicate (appears multiple times) | Series of all matching values |

This inconsistency in return type can complicate downstream code — a function expecting a scalar may unexpectedly receive a Series.

The same behavior applies to **DataFrame** row (and column) selection with `loc`:

- Duplicate row label → returns a DataFrame.
- Unique row label → returns a Series.

## Key Points

- Duplicate index labels are allowed but not required.
- `index.is_unique` returns `True` if all labels are distinct.
- Indexing a **unique** label returns a scalar (or Series for a DataFrame row).
- Indexing a **duplicate** label returns a Series (or DataFrame for a DataFrame row).
- The variable return type is a potential source of bugs when labels may or may not be duplicated.

In [3]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [4]:
obj.index.is_unique

False

In [5]:
obj["a"]  # duplicate label → returns a Series

a    0
a    1
dtype: int64

In [6]:
obj["c"]  # unique label → returns a scalar

np.int64(4)

In [7]:
df = pd.DataFrame(
    np.random.standard_normal((5, 3)),
    index=["a", "a", "b", "b", "c"]
)

df

          0         1         2
a  1.319838 -1.001863 -0.452913
a  0.299570 -1.100476 -1.413490
b  0.997403 -0.721230 -0.317000
b -0.536654 -1.405458 -0.082218
c  1.014441 -0.529021 -0.831361

In [8]:
df.loc["b"]  # duplicate row label → returns a DataFrame

          0         1         2
b  0.997403 -0.721230 -0.317000
b -0.536654 -1.405458 -0.082218

In [9]:
df.loc["c"]  # unique row label → returns a Series

0    1.014441
1   -0.529021
2   -0.831361
Name: c, dtype: float64